name: beyazalan
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.7
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#194073"
  image: assets/slice.png

flutter_icons:
  # flutter pub run flutter_launcher_icons:main
  image_path: "assets/AppIcon.png"
  android: false
  ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
